Date::DATE_FORMATS[:short] = "%b %d"
Date::DATE_FORMATS[:medium] = "%B %-d, %Y"
Date::DATE_FORMATS[:long] = "%A, %B %-d, %Y"
Date::DATE_FORMATS[:numeric] = "%-m/%-d/%y"
Time::DATE_FORMATS[:numeric] = "%-m/%-d/%y"