# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 6b9f7f340e3f4cec61c87d05767961708eebd4d4c64f0a44fc6da98ddd996ff3d67c53e358ea1ddb92ceae06e2e94595848d0ec021b30c46ce38d3ff9a1cf846

test:
  secret_key_base: e5e49a38c101813e3ee20c6bba64d5b7aa81d3af7c87f32d323dcb0690738a4a3ba39b4a4b6888643fae42d177093184ec68a12f4cd675e728d3d470eae1d12c

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
